import '@/styles/globals.scss';
import type { Metadata } from 'next'

//--------------------- settings for fontawesome-------------------
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false
//-----------------------------------------------------------------

import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { barlow } from '@/utils/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={barlow.className}>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
